name: judotimer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  go_router:
  flutter_riverpod:
  flutter_hooks:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  segment_display: ^0.5.0
  riverpod_annotation: ^2.3.5
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.3+1

flutter_native_splash:
  color: '#add8e6'
  image: 'assets/images/hoshikawa.png'
  color_dark: '#262626'
  image_dark: 'assets/images/hoshikawa.png'
  fullscreen: true
  android_12:
    icon_background_color: '#add8e6'
    image: 'assets/images/hoshikawa.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/images/hoshikawa.png'

flutter:
  assets:
    - assets/images/
    # - assets/fonts/
  fonts:
    - family: Dangrek
      fonts:
      - asset: assets/fonts/Dangrek/Dangrek-Regular.ttf
    - family: Zen_Old_Mincho
      fonts:
      - asset: assets/fonts/Zen_Old_Mincho/ZenOldMincho-Medium.ttf
        weight: 500
    - family: Noto_Sans_JP
      fonts:
      - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Medium.ttf
        weight: 500

  uses-material-design: true
